/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;
import Ficha.Player;
import Ficha.ficha;
import java.awt.Color;
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class Estratego extends javax.swing.JFrame {
     String boton;   
     ficha tablero[][];
     ArrayList<Player> jugadores;
     int f1,c1,f2,c2,turno;
     boolean primero=false;
     
     
    /**
     * Creates new form Estratego
     */
    public Estratego() {
        initComponents();
        tablero=new ficha[10][10];
        
        jugadores=new ArrayList<>();
        turno=2;
        jp1.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);   
        jp2.setVisible(false);
        jp5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        btnIngresar2 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jp3 = new javax.swing.JPanel();
        btnRegistrar2 = new javax.swing.JButton();
        btnRegresar2 = new javax.swing.JButton();
        txtUser2 = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JTextField();
        txtConfirmacion = new javax.swing.JTextField();
        jp4 = new javax.swing.JPanel();
        btnPartidaN = new javax.swing.JButton();
        jp5 = new javax.swing.JPanel();
        p00 = new javax.swing.JButton();
        p01 = new javax.swing.JButton();
        p03 = new javax.swing.JButton();
        p02 = new javax.swing.JButton();
        p05 = new javax.swing.JButton();
        p04 = new javax.swing.JButton();
        p07 = new javax.swing.JButton();
        p06 = new javax.swing.JButton();
        p09 = new javax.swing.JButton();
        p08 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p17 = new javax.swing.JButton();
        p16 = new javax.swing.JButton();
        p19 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p18 = new javax.swing.JButton();
        p21 = new javax.swing.JButton();
        p23 = new javax.swing.JButton();
        p22 = new javax.swing.JButton();
        p25 = new javax.swing.JButton();
        p24 = new javax.swing.JButton();
        p27 = new javax.swing.JButton();
        p26 = new javax.swing.JButton();
        p29 = new javax.swing.JButton();
        p20 = new javax.swing.JButton();
        p28 = new javax.swing.JButton();
        p31 = new javax.swing.JButton();
        p33 = new javax.swing.JButton();
        p32 = new javax.swing.JButton();
        p35 = new javax.swing.JButton();
        p34 = new javax.swing.JButton();
        p37 = new javax.swing.JButton();
        p36 = new javax.swing.JButton();
        p39 = new javax.swing.JButton();
        p30 = new javax.swing.JButton();
        p38 = new javax.swing.JButton();
        p41 = new javax.swing.JButton();
        p43 = new javax.swing.JButton();
        p42 = new javax.swing.JButton();
        p45 = new javax.swing.JButton();
        p44 = new javax.swing.JButton();
        p47 = new javax.swing.JButton();
        p46 = new javax.swing.JButton();
        p49 = new javax.swing.JButton();
        p40 = new javax.swing.JButton();
        p48 = new javax.swing.JButton();
        p60 = new javax.swing.JButton();
        p68 = new javax.swing.JButton();
        p71 = new javax.swing.JButton();
        p73 = new javax.swing.JButton();
        p72 = new javax.swing.JButton();
        p75 = new javax.swing.JButton();
        p74 = new javax.swing.JButton();
        p77 = new javax.swing.JButton();
        p76 = new javax.swing.JButton();
        p79 = new javax.swing.JButton();
        p70 = new javax.swing.JButton();
        p78 = new javax.swing.JButton();
        p81 = new javax.swing.JButton();
        p83 = new javax.swing.JButton();
        p82 = new javax.swing.JButton();
        p85 = new javax.swing.JButton();
        p84 = new javax.swing.JButton();
        p87 = new javax.swing.JButton();
        p86 = new javax.swing.JButton();
        p89 = new javax.swing.JButton();
        p80 = new javax.swing.JButton();
        p88 = new javax.swing.JButton();
        p91 = new javax.swing.JButton();
        p93 = new javax.swing.JButton();
        p92 = new javax.swing.JButton();
        p95 = new javax.swing.JButton();
        p94 = new javax.swing.JButton();
        p51 = new javax.swing.JButton();
        p97 = new javax.swing.JButton();
        p53 = new javax.swing.JButton();
        p96 = new javax.swing.JButton();
        p52 = new javax.swing.JButton();
        p99 = new javax.swing.JButton();
        p55 = new javax.swing.JButton();
        p54 = new javax.swing.JButton();
        p57 = new javax.swing.JButton();
        p56 = new javax.swing.JButton();
        p50 = new javax.swing.JButton();
        p90 = new javax.swing.JButton();
        p98 = new javax.swing.JButton();
        p59 = new javax.swing.JButton();
        p58 = new javax.swing.JButton();
        p61 = new javax.swing.JButton();
        p63 = new javax.swing.JButton();
        p62 = new javax.swing.JButton();
        p65 = new javax.swing.JButton();
        p64 = new javax.swing.JButton();
        p67 = new javax.swing.JButton();
        p66 = new javax.swing.JButton();
        p69 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1658, 1940));

        jp1.setPreferredSize(new java.awt.Dimension(1628, 930));

        btnIngresar.setText("Log In");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Crear Player");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(585, 585, 585)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(950, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(btnIngresar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        jp2.setPreferredSize(new java.awt.Dimension(1628, 930));

        btnIngresar2.setText("Ingresar");
        btnIngresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar2ActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(552, 552, 552)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(btnIngresar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar))
                    .addComponent(txtPassword))
                .addContainerGap(916, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar2)
                    .addComponent(btnRegresar))
                .addContainerGap(498, Short.MAX_VALUE))
        );

        jp3.setPreferredSize(new java.awt.Dimension(1628, 930));

        btnRegistrar2.setText("Registrar");
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar2ActionPerformed(evt);
            }
        });

        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser2)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addComponent(btnRegistrar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegresar2))
                    .addComponent(txtPassword2)
                    .addComponent(txtConfirmacion))
                .addContainerGap(893, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar2)
                    .addComponent(btnRegresar2))
                .addContainerGap(514, Short.MAX_VALUE))
        );

        jp4.setPreferredSize(new java.awt.Dimension(1628, 930));

        btnPartidaN.setText("Partida Nueva");
        btnPartidaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidaNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnPartidaN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1392, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnPartidaN)
                .addContainerGap(776, Short.MAX_VALUE))
        );

        jp5.setPreferredSize(new java.awt.Dimension(1628, 930));

        p00.setBackground(new java.awt.Color(204, 0, 0));
        p00.setText("jButton1");
        p00.setPreferredSize(new java.awt.Dimension(63, 23));
        p00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p00ActionPerformed(evt);
            }
        });

        p01.setBackground(new java.awt.Color(204, 0, 0));
        p01.setText("jButton1");
        p01.setPreferredSize(new java.awt.Dimension(63, 23));

        p03.setBackground(new java.awt.Color(204, 0, 0));
        p03.setText("jButton1");
        p03.setPreferredSize(new java.awt.Dimension(63, 23));

        p02.setBackground(new java.awt.Color(204, 0, 0));
        p02.setText("jButton1");
        p02.setPreferredSize(new java.awt.Dimension(63, 23));

        p05.setBackground(new java.awt.Color(204, 0, 0));
        p05.setText("jButton1");
        p05.setPreferredSize(new java.awt.Dimension(63, 23));

        p04.setBackground(new java.awt.Color(204, 0, 0));
        p04.setText("jButton1");
        p04.setPreferredSize(new java.awt.Dimension(63, 23));

        p07.setBackground(new java.awt.Color(204, 0, 0));
        p07.setText("jButton1");
        p07.setPreferredSize(new java.awt.Dimension(63, 23));

        p06.setBackground(new java.awt.Color(204, 0, 0));
        p06.setText("jButton1");
        p06.setPreferredSize(new java.awt.Dimension(63, 23));

        p09.setBackground(new java.awt.Color(204, 0, 0));
        p09.setText("jButton1");
        p09.setPreferredSize(new java.awt.Dimension(63, 23));

        p08.setBackground(new java.awt.Color(204, 0, 0));
        p08.setText("jButton1");
        p08.setPreferredSize(new java.awt.Dimension(63, 23));

        p11.setBackground(new java.awt.Color(204, 0, 0));
        p11.setText("jButton1");
        p11.setPreferredSize(new java.awt.Dimension(63, 23));

        p13.setBackground(new java.awt.Color(204, 0, 0));
        p13.setText("jButton1");
        p13.setPreferredSize(new java.awt.Dimension(63, 23));

        p12.setBackground(new java.awt.Color(204, 0, 0));
        p12.setText("jButton1");
        p12.setPreferredSize(new java.awt.Dimension(63, 23));

        p15.setBackground(new java.awt.Color(204, 0, 0));
        p15.setText("jButton1");
        p15.setPreferredSize(new java.awt.Dimension(63, 23));

        p14.setBackground(new java.awt.Color(204, 0, 0));
        p14.setText("jButton1");
        p14.setPreferredSize(new java.awt.Dimension(63, 23));

        p17.setBackground(new java.awt.Color(204, 0, 0));
        p17.setText("jButton1");
        p17.setPreferredSize(new java.awt.Dimension(63, 23));

        p16.setBackground(new java.awt.Color(204, 0, 0));
        p16.setText("jButton1");
        p16.setPreferredSize(new java.awt.Dimension(63, 23));

        p19.setBackground(new java.awt.Color(204, 0, 0));
        p19.setText("jButton1");
        p19.setPreferredSize(new java.awt.Dimension(63, 23));

        p10.setBackground(new java.awt.Color(204, 0, 0));
        p10.setText("jButton1");
        p10.setPreferredSize(new java.awt.Dimension(63, 23));

        p18.setBackground(new java.awt.Color(204, 0, 0));
        p18.setText("jButton1");
        p18.setPreferredSize(new java.awt.Dimension(63, 23));

        p21.setBackground(new java.awt.Color(204, 0, 0));
        p21.setText("jButton1");
        p21.setPreferredSize(new java.awt.Dimension(63, 23));

        p23.setBackground(new java.awt.Color(204, 0, 0));
        p23.setText("jButton1");
        p23.setPreferredSize(new java.awt.Dimension(63, 23));

        p22.setBackground(new java.awt.Color(204, 0, 0));
        p22.setText("jButton1");
        p22.setPreferredSize(new java.awt.Dimension(63, 23));

        p25.setBackground(new java.awt.Color(204, 0, 0));
        p25.setText("jButton1");
        p25.setPreferredSize(new java.awt.Dimension(63, 23));

        p24.setBackground(new java.awt.Color(204, 0, 0));
        p24.setText("jButton1");
        p24.setPreferredSize(new java.awt.Dimension(63, 23));

        p27.setBackground(new java.awt.Color(204, 0, 0));
        p27.setText("jButton1");
        p27.setPreferredSize(new java.awt.Dimension(63, 23));

        p26.setBackground(new java.awt.Color(204, 0, 0));
        p26.setText("jButton1");
        p26.setPreferredSize(new java.awt.Dimension(63, 23));

        p29.setBackground(new java.awt.Color(204, 0, 0));
        p29.setText("jButton1");
        p29.setPreferredSize(new java.awt.Dimension(63, 23));

        p20.setBackground(new java.awt.Color(204, 0, 0));
        p20.setText("jButton1");
        p20.setPreferredSize(new java.awt.Dimension(63, 23));

        p28.setBackground(new java.awt.Color(204, 0, 0));
        p28.setText("jButton1");
        p28.setPreferredSize(new java.awt.Dimension(63, 23));

        p31.setBackground(new java.awt.Color(204, 0, 0));
        p31.setText("jButton1");
        p31.setPreferredSize(new java.awt.Dimension(63, 23));

        p33.setBackground(new java.awt.Color(204, 0, 0));
        p33.setText("jButton1");
        p33.setPreferredSize(new java.awt.Dimension(63, 23));

        p32.setBackground(new java.awt.Color(204, 0, 0));
        p32.setText("jButton1");
        p32.setPreferredSize(new java.awt.Dimension(63, 23));

        p35.setBackground(new java.awt.Color(204, 0, 0));
        p35.setText("jButton1");
        p35.setPreferredSize(new java.awt.Dimension(63, 23));

        p34.setBackground(new java.awt.Color(204, 0, 0));
        p34.setText("jButton1");
        p34.setPreferredSize(new java.awt.Dimension(63, 23));

        p37.setBackground(new java.awt.Color(204, 0, 0));
        p37.setText("jButton1");
        p37.setPreferredSize(new java.awt.Dimension(63, 23));

        p36.setBackground(new java.awt.Color(204, 0, 0));
        p36.setText("jButton1");
        p36.setPreferredSize(new java.awt.Dimension(63, 23));

        p39.setBackground(new java.awt.Color(204, 0, 0));
        p39.setText("jButton1");
        p39.setPreferredSize(new java.awt.Dimension(63, 23));

        p30.setBackground(new java.awt.Color(204, 0, 0));
        p30.setText("jButton1");
        p30.setPreferredSize(new java.awt.Dimension(63, 23));

        p38.setBackground(new java.awt.Color(204, 0, 0));
        p38.setText("jButton1");
        p38.setPreferredSize(new java.awt.Dimension(63, 23));

        p41.setText("jButton1");
        p41.setPreferredSize(new java.awt.Dimension(63, 23));

        p43.setText("jButton1");
        p43.setPreferredSize(new java.awt.Dimension(63, 23));

        p42.setText("jButton1");
        p42.setPreferredSize(new java.awt.Dimension(63, 23));

        p45.setText("jButton1");
        p45.setPreferredSize(new java.awt.Dimension(63, 23));

        p44.setText("jButton1");
        p44.setPreferredSize(new java.awt.Dimension(63, 23));

        p47.setText("jButton1");
        p47.setPreferredSize(new java.awt.Dimension(63, 23));

        p46.setText("jButton1");
        p46.setPreferredSize(new java.awt.Dimension(63, 23));

        p49.setText("jButton1");
        p49.setPreferredSize(new java.awt.Dimension(63, 23));

        p40.setText("jButton1");
        p40.setPreferredSize(new java.awt.Dimension(63, 23));
        p40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p40ActionPerformed(evt);
            }
        });

        p48.setText("jButton1");
        p48.setPreferredSize(new java.awt.Dimension(63, 23));

        p60.setBackground(new java.awt.Color(51, 0, 204));
        p60.setText("jButton1");
        p60.setPreferredSize(new java.awt.Dimension(63, 23));

        p68.setBackground(new java.awt.Color(51, 0, 204));
        p68.setText("jButton1");
        p68.setPreferredSize(new java.awt.Dimension(63, 23));

        p71.setBackground(new java.awt.Color(51, 0, 204));
        p71.setText("jButton1");
        p71.setPreferredSize(new java.awt.Dimension(63, 23));

        p73.setBackground(new java.awt.Color(51, 0, 204));
        p73.setText("jButton1");
        p73.setPreferredSize(new java.awt.Dimension(63, 23));

        p72.setBackground(new java.awt.Color(51, 0, 204));
        p72.setText("jButton1");
        p72.setPreferredSize(new java.awt.Dimension(63, 23));

        p75.setBackground(new java.awt.Color(51, 0, 204));
        p75.setText("jButton1");
        p75.setPreferredSize(new java.awt.Dimension(63, 23));

        p74.setBackground(new java.awt.Color(51, 0, 204));
        p74.setText("jButton1");
        p74.setPreferredSize(new java.awt.Dimension(63, 23));

        p77.setBackground(new java.awt.Color(51, 0, 204));
        p77.setText("jButton1");
        p77.setPreferredSize(new java.awt.Dimension(63, 23));

        p76.setBackground(new java.awt.Color(51, 0, 204));
        p76.setText("jButton1");
        p76.setPreferredSize(new java.awt.Dimension(63, 23));

        p79.setBackground(new java.awt.Color(51, 0, 204));
        p79.setText("jButton1");
        p79.setPreferredSize(new java.awt.Dimension(63, 23));

        p70.setBackground(new java.awt.Color(51, 0, 204));
        p70.setText("jButton1");
        p70.setPreferredSize(new java.awt.Dimension(63, 23));

        p78.setBackground(new java.awt.Color(51, 0, 204));
        p78.setText("jButton1");
        p78.setPreferredSize(new java.awt.Dimension(63, 23));

        p81.setBackground(new java.awt.Color(51, 0, 204));
        p81.setText("jButton1");
        p81.setPreferredSize(new java.awt.Dimension(63, 23));

        p83.setBackground(new java.awt.Color(51, 0, 204));
        p83.setText("jButton1");
        p83.setPreferredSize(new java.awt.Dimension(63, 23));

        p82.setBackground(new java.awt.Color(51, 0, 204));
        p82.setText("jButton1");
        p82.setPreferredSize(new java.awt.Dimension(63, 23));

        p85.setBackground(new java.awt.Color(51, 0, 204));
        p85.setText("jButton1");
        p85.setPreferredSize(new java.awt.Dimension(63, 23));

        p84.setBackground(new java.awt.Color(51, 0, 204));
        p84.setText("jButton1");
        p84.setPreferredSize(new java.awt.Dimension(63, 23));

        p87.setBackground(new java.awt.Color(51, 0, 204));
        p87.setText("jButton1");
        p87.setPreferredSize(new java.awt.Dimension(63, 23));

        p86.setBackground(new java.awt.Color(51, 0, 204));
        p86.setText("jButton1");
        p86.setPreferredSize(new java.awt.Dimension(63, 23));

        p89.setBackground(new java.awt.Color(51, 0, 204));
        p89.setText("jButton1");
        p89.setPreferredSize(new java.awt.Dimension(63, 23));

        p80.setBackground(new java.awt.Color(51, 0, 204));
        p80.setText("jButton1");
        p80.setPreferredSize(new java.awt.Dimension(63, 23));

        p88.setBackground(new java.awt.Color(51, 0, 204));
        p88.setText("jButton1");
        p88.setPreferredSize(new java.awt.Dimension(63, 23));

        p91.setBackground(new java.awt.Color(51, 0, 204));
        p91.setText("jButton1");
        p91.setPreferredSize(new java.awt.Dimension(63, 23));

        p93.setBackground(new java.awt.Color(51, 0, 204));
        p93.setText("jButton1");
        p93.setPreferredSize(new java.awt.Dimension(63, 23));

        p92.setBackground(new java.awt.Color(51, 0, 204));
        p92.setText("jButton1");
        p92.setPreferredSize(new java.awt.Dimension(63, 23));

        p95.setBackground(new java.awt.Color(51, 0, 204));
        p95.setText("jButton1");
        p95.setPreferredSize(new java.awt.Dimension(63, 23));

        p94.setBackground(new java.awt.Color(51, 0, 204));
        p94.setText("jButton1");
        p94.setPreferredSize(new java.awt.Dimension(63, 23));

        p51.setText("jButton1");
        p51.setPreferredSize(new java.awt.Dimension(63, 23));

        p97.setBackground(new java.awt.Color(51, 0, 204));
        p97.setText("jButton1");
        p97.setPreferredSize(new java.awt.Dimension(63, 23));

        p53.setText("jButton1");
        p53.setPreferredSize(new java.awt.Dimension(63, 23));

        p96.setBackground(new java.awt.Color(51, 0, 204));
        p96.setText("jButton1");
        p96.setPreferredSize(new java.awt.Dimension(63, 23));

        p52.setText("jButton1");
        p52.setPreferredSize(new java.awt.Dimension(63, 23));

        p99.setBackground(new java.awt.Color(51, 0, 204));
        p99.setText("jButton1");
        p99.setPreferredSize(new java.awt.Dimension(63, 23));

        p55.setText("jButton1");
        p55.setPreferredSize(new java.awt.Dimension(63, 23));

        p54.setText("jButton1");
        p54.setPreferredSize(new java.awt.Dimension(63, 23));

        p57.setText("jButton1");
        p57.setPreferredSize(new java.awt.Dimension(63, 23));

        p56.setText("jButton1");
        p56.setPreferredSize(new java.awt.Dimension(63, 23));

        p50.setText("jButton1");
        p50.setPreferredSize(new java.awt.Dimension(63, 23));

        p90.setBackground(new java.awt.Color(51, 0, 204));
        p90.setText("jButton1");
        p90.setPreferredSize(new java.awt.Dimension(63, 23));

        p98.setBackground(new java.awt.Color(51, 0, 204));
        p98.setText("jButton1");
        p98.setPreferredSize(new java.awt.Dimension(63, 23));

        p59.setText("jButton1");
        p59.setPreferredSize(new java.awt.Dimension(63, 23));

        p58.setText("jButton1");
        p58.setPreferredSize(new java.awt.Dimension(63, 23));

        p61.setBackground(new java.awt.Color(51, 0, 204));
        p61.setText("jButton1");
        p61.setPreferredSize(new java.awt.Dimension(63, 23));

        p63.setBackground(new java.awt.Color(51, 0, 204));
        p63.setText("jButton1");
        p63.setPreferredSize(new java.awt.Dimension(63, 23));

        p62.setBackground(new java.awt.Color(51, 0, 204));
        p62.setText("jButton1");
        p62.setPreferredSize(new java.awt.Dimension(63, 23));

        p65.setBackground(new java.awt.Color(51, 0, 204));
        p65.setText("jButton1");
        p65.setPreferredSize(new java.awt.Dimension(63, 23));

        p64.setBackground(new java.awt.Color(51, 0, 204));
        p64.setText("jButton1");
        p64.setPreferredSize(new java.awt.Dimension(63, 23));

        p67.setBackground(new java.awt.Color(51, 0, 204));
        p67.setText("jButton1");
        p67.setPreferredSize(new java.awt.Dimension(63, 23));

        p66.setBackground(new java.awt.Color(51, 0, 204));
        p66.setPreferredSize(new java.awt.Dimension(63, 23));

        p69.setBackground(new java.awt.Color(51, 0, 204));
        p69.setText("jButton1");
        p69.setPreferredSize(new java.awt.Dimension(63, 23));

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addComponent(p00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(746, Short.MAX_VALUE))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p80, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p90, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1614, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1594, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(990, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(970, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       jp1.setVisible(false);
       jp2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        jp1.setVisible(false);
        jp3.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        jp3.setVisible(false);
        jp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void btnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar2ActionPerformed
       String user= txtUser2.getText();
       String pass=txtPassword2.getText();
       String passcon=txtConfirmacion.getText();
       if(user.length()>0 && pass.length()>0&& passcon.length()>0){
        addPlayer(user,pass,passcon);
       }else{
       JOptionPane.showMessageDialog(null,"Ingrese todos los datos por favor!");
       }
       
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrar2ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        jp2.setVisible(false);
        jp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIngresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar2ActionPerformed
        String user=txtUser.getText();
        String pass=txtPassword.getText();
        Player usuario=search(user);
        if(user.length()>0 && pass.length()>0){
        Log(usuario,pass);}else{
        JOptionPane.showMessageDialog(null,"Ingrese todos los datos por favor|");
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar2ActionPerformed

    private void btnPartidaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidaNActionPerformed
       jp4.setVisible(false);
       jp5.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPartidaNActionPerformed

    private void p00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p00ActionPerformed
        try {
            p00.setName("p00");
             if( turno%2==0){
            if(primero){
                  f2=0;c2=0;
                  if(move(f1,c1,f2,c2)){
                      System.out.println("Entro");
                   moveFi(boton,Color.gray);
                    moveFi("p00",Color.red);
                    primero=false;
                   f1=-1;c1=-1;f2=-1;c2=-1;
                  }
            }else{
                boton="p00";
                primero=true;
            }
        }
        } catch (NullPointerException e) {
            primero=false;
            JOptionPane.showMessageDialog(null,"Error: movimiento no realizado!");
        }
       
    }//GEN-LAST:event_p00ActionPerformed

    private void p40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p40ActionPerformed
        try {
            if(turno%2==0){
            if(primero){
                  f2=4;c2=0;
                  if(move(f1,c1,f2,c2)){
                      System.out.println("Entro en P40");
                      System.out.println("El boton: "+boton);
                    moveFi(boton,Color.gray);
                    moveFi("p40",Color.red);
                   primero=false;
                   f1=-1;c1=-1;f2=-1;c2=-1;
                  }
            }else{
                boton="p40";
                primero=true;
            }
        }
        } catch (NullPointerException e) {
            primero=false;
            JOptionPane.showMessageDialog(null,"Error: movimiento no realizado!");
        }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_p40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estratego().setVisible(true);
            }
        });
    }

    
    //Funciones Extras
    public Player search(String user){
            for(Player p:jugadores){
                if(p.getUser().equalsIgnoreCase(user))
                    return p;
            }
            return null;
        }
    private void addPlayer(String user,String pass,String passcon){
    Player jugador=search(user);
    if(jugador==null){
        if(pass.equals(passcon)&& pass.length()==5){
            jugadores.add(new Player(user,pass));
            jp3.setVisible(false);
            jp1.setVisible(true);
            txtUser2.setText("");
            txtPassword2.setText("");
            txtConfirmacion.setText("");
        }else{
              txtPassword2.setText("");
              txtConfirmacion.setText("");
        JOptionPane.showMessageDialog(null,"Error: Claves no son igulaes!");
        }
    }else{
        txtUser2.setText("");
        JOptionPane.showMessageDialog(null,"Error: Usuario "+user+" ya existe! Intenta con otro!");
    }
    }
    void Log(Player usuario,String pass){
        try {
            if(usuario!=null){
            if(usuario.getPassword().equals(pass)){
            Player.LOGGED_USER=usuario.getUser();
             jp2.setVisible(false);
             jp4.setVisible(true);}
            else{
                JOptionPane.showMessageDialog(null,"Error: Clave incorrecta! Intente de nuevo");
                txtPassword.setText("");}
        }
        } catch (NullPointerException e){   
        JOptionPane.showMessageDialog(null,"Error: Usuario "+txtUser.getText()+" no existe!");
         txtPassword.setText("");
         txtUser.setText("");
        }
        
        }
    boolean move(int fila1,int columna1,int fila2,int columna2){
    return true;
    }
    void moveFi(String nombre, Color color){
        System.out.println("Nombre: "+nombre);
    if(nombre.equals("p00")){
        p00.setBackground(color);
    }else if(nombre.equals("p01")){
        p01.setBackground(color);
    }else if(nombre.equals("p02")){
        p02.setBackground(color);
    }else if(nombre.equals("p03")){
        p03.setBackground(color);
    }else if(nombre.equals("p04")){
        p04.setBackground(color);
    }else if(nombre.equals("p05")){
        p05.setBackground(color);
    }else if(nombre.equals("p06")){
        p06.setBackground(color);
    }else if(nombre.equals("p07")){
        p07.setBackground(color);
    }else if(nombre.equals("p08")){
        p08.setBackground(color);
    }else if(nombre.equals("p09")){
        p09.setBackground(color);
    }else if(nombre.equals("p10")){
        p10.setBackground(color);
    }else if(nombre.equals("p11")){
        p11.setBackground(color);
    }else if(nombre.equals("p12")){
        p12.setBackground(color);
    }else if(nombre.equals("p13")){
        p13.setBackground(color);
    }else if(nombre.equals("p14")){
        p14.setBackground(color);
    }else if(nombre.equals("p15")){
        p15.setBackground(color);
    }else if(nombre.equals("p16")){
        p16.setBackground(color);
    }else if(nombre.equals("p17")){
        p17.setBackground(color);
    }else if(nombre.equals("p18")){
        p18.setBackground(color);
    }else if(nombre.equals("p19")){
        p19.setBackground(color);
    }else if(nombre.equals("p20")){
        p20.setBackground(color);
    }else if(nombre.equals("p21")){
        p21.setBackground(color);
    }else if(nombre.equals("p22")){
        p22.setBackground(color);
    }else if(nombre.equals("p23")){
        p23.setBackground(color);
    }else if(nombre.equals("p24")){
        p24.setBackground(color);
    }else if(nombre.equals("p25")){
        p25.setBackground(color);
    }else if(nombre.equals("p26")){
        p26.setBackground(color);
    }else if(nombre.equals("p27")){
        p27.setBackground(color);
    }else if(nombre.equals("p28")){
        p28.setBackground(color);
    }else if(nombre.equals("p29")){
        p29.setBackground(color);
    }else if(nombre.equals("p30")){
        p30.setBackground(color);
    }else if(nombre.equals("p31")){
        p31.setBackground(color);
    }else if(nombre.equals("p32")){
        p32.setBackground(color);
    }else if(nombre.equals("p33")){
        p33.setBackground(color);
    }else if(nombre.equals("p34")){
        p34.setBackground(color);
    }else if(nombre.equals("p35")){
        p35.setBackground(color);
    }else if(nombre.equals("p36")){
        p36.setBackground(color);
    }else if(nombre.equals("p37")){
        p37.setBackground(color);
    }else if(nombre.equals("p38")){
        p38.setBackground(color);
    }else if(nombre.equals("p39")){
        p39.setBackground(color);
    }else if(nombre.equals("p40")){
        p40.setBackground(color);
    }else if(nombre.equals("p41")){
        p41.setBackground(color);
    }else if(nombre.equals("p42")){
        p42.setBackground(color);
    }else if(nombre.equals("p43")){
        p43.setBackground(color);
    }else if(nombre.equals("p44")){
        p44.setBackground(color);
    }else if(nombre.equals("p45")){
        p00.setBackground(color);
    }else if(nombre.equals("p46")){
        p00.setBackground(color);
    }else if(nombre.equals("p47")){
        p00.setBackground(color);
    }else if(nombre.equals("p48")){
        p00.setBackground(color);
    }else if(nombre.equals("p49")){
        p00.setBackground(color);
    }else if(nombre.equals("p50")){
        p00.setBackground(color);
    }else if(nombre.equals("p51")){
        p00.setBackground(color);
    }else if(nombre.equals("p52")){
        p00.setBackground(color);
    }else if(nombre.equals("p53")){
        p00.setBackground(color);
    }else if(nombre.equals("p54")){
        p00.setBackground(color);
    }else if(nombre.equals("p55")){
        p00.setBackground(color);
    }else if(nombre.equals("p56")){
        p00.setBackground(color);
    }else if(nombre.equals("p57")){
        p00.setBackground(color);
    }else if(nombre.equals("p58")){
        p00.setBackground(color);
    }else if(nombre.equals("p59")){
        p00.setBackground(color);
    }else if(nombre.equals("p60")){
        p00.setBackground(color);
    }else if(nombre.equals("p61")){
        p00.setBackground(color);
    }else if(nombre.equals("p62")){
        p00.setBackground(color);
    }else if(nombre.equals("p63")){
        p00.setBackground(color);
    }else if(nombre.equals("p64")){
        p00.setBackground(color);
    }else if(nombre.equals("p65")){
        p00.setBackground(color);
    }else if(nombre.equals("p66")){
        p00.setBackground(color);
    }else if(nombre.equals("p67")){
        p00.setBackground(color);
    }else if(nombre.equals("p68")){
        p00.setBackground(color);
    }else if(nombre.equals("p69")){
        p00.setBackground(color);
    }else if(nombre.equals("p70")){
        p00.setBackground(color);
    }else if(nombre.equals("p71")){
        p00.setBackground(color);
    }else if(nombre.equals("p72")){
        p00.setBackground(color);
    }else if(nombre.equals("p73")){
        p00.setBackground(color);
    }else if(nombre.equals("p74")){
        p00.setBackground(color);
    }else if(nombre.equals("p75")){
        p00.setBackground(color);
    }else if(nombre.equals("p76")){
        p00.setBackground(color);
    }else if(nombre.equals("p77")){
        p00.setBackground(color);
    }else if(nombre.equals("p78")){
        p00.setBackground(color);
    }else if(nombre.equals("p79")){
        p00.setBackground(color);
    }else if(nombre.equals("p80")){
        p00.setBackground(color);
    }else if(nombre.equals("p81")){
        p00.setBackground(color);
    }else if(nombre.equals("p82")){
        p00.setBackground(color);
    }else if(nombre.equals("p83")){
        p00.setBackground(color);
    }else if(nombre.equals("p84")){
        p00.setBackground(color);
    }else if(nombre.equals("p85")){
        p00.setBackground(color);
    }else if(nombre.equals("p86")){
        p00.setBackground(color);
    }else if(nombre.equals("p87")){
        p00.setBackground(color);
    }else if(nombre.equals("p88")){
        p00.setBackground(color);
    }else if(nombre.equals("p89")){
        p00.setBackground(color);
    }else if(nombre.equals("p90")){
        p00.setBackground(color);
    }else if(nombre.equals("p91")){
        p00.setBackground(color);
    }else if(nombre.equals("p92")){
        p00.setBackground(color);
    }else if(nombre.equals("p93")){
        p00.setBackground(color);
    }else if(nombre.equals("p94")){
        p00.setBackground(color);
    }else if(nombre.equals("p95")){
        p00.setBackground(color);
    }else if(nombre.equals("p96")){
        p00.setBackground(color);
    }else if(nombre.equals("p97")){
        p00.setBackground(color);
    }else if(nombre.equals("p98")){
        p00.setBackground(color);
    }else if(nombre.equals("p99")){
        p00.setBackground(color);
    }
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar2;
    private javax.swing.JButton btnPartidaN;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JButton p00;
    private javax.swing.JButton p01;
    private javax.swing.JButton p02;
    private javax.swing.JButton p03;
    private javax.swing.JButton p04;
    private javax.swing.JButton p05;
    private javax.swing.JButton p06;
    private javax.swing.JButton p07;
    private javax.swing.JButton p08;
    private javax.swing.JButton p09;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p16;
    private javax.swing.JButton p17;
    private javax.swing.JButton p18;
    private javax.swing.JButton p19;
    private javax.swing.JButton p20;
    private javax.swing.JButton p21;
    private javax.swing.JButton p22;
    private javax.swing.JButton p23;
    private javax.swing.JButton p24;
    private javax.swing.JButton p25;
    private javax.swing.JButton p26;
    private javax.swing.JButton p27;
    private javax.swing.JButton p28;
    private javax.swing.JButton p29;
    private javax.swing.JButton p30;
    private javax.swing.JButton p31;
    private javax.swing.JButton p32;
    private javax.swing.JButton p33;
    private javax.swing.JButton p34;
    private javax.swing.JButton p35;
    private javax.swing.JButton p36;
    private javax.swing.JButton p37;
    private javax.swing.JButton p38;
    private javax.swing.JButton p39;
    private javax.swing.JButton p40;
    private javax.swing.JButton p41;
    private javax.swing.JButton p42;
    private javax.swing.JButton p43;
    private javax.swing.JButton p44;
    private javax.swing.JButton p45;
    private javax.swing.JButton p46;
    private javax.swing.JButton p47;
    private javax.swing.JButton p48;
    private javax.swing.JButton p49;
    private javax.swing.JButton p50;
    private javax.swing.JButton p51;
    private javax.swing.JButton p52;
    private javax.swing.JButton p53;
    private javax.swing.JButton p54;
    private javax.swing.JButton p55;
    private javax.swing.JButton p56;
    private javax.swing.JButton p57;
    private javax.swing.JButton p58;
    private javax.swing.JButton p59;
    private javax.swing.JButton p60;
    private javax.swing.JButton p61;
    private javax.swing.JButton p62;
    private javax.swing.JButton p63;
    private javax.swing.JButton p64;
    private javax.swing.JButton p65;
    private javax.swing.JButton p66;
    private javax.swing.JButton p67;
    private javax.swing.JButton p68;
    private javax.swing.JButton p69;
    private javax.swing.JButton p70;
    private javax.swing.JButton p71;
    private javax.swing.JButton p72;
    private javax.swing.JButton p73;
    private javax.swing.JButton p74;
    private javax.swing.JButton p75;
    private javax.swing.JButton p76;
    private javax.swing.JButton p77;
    private javax.swing.JButton p78;
    private javax.swing.JButton p79;
    private javax.swing.JButton p80;
    private javax.swing.JButton p81;
    private javax.swing.JButton p82;
    private javax.swing.JButton p83;
    private javax.swing.JButton p84;
    private javax.swing.JButton p85;
    private javax.swing.JButton p86;
    private javax.swing.JButton p87;
    private javax.swing.JButton p88;
    private javax.swing.JButton p89;
    private javax.swing.JButton p90;
    private javax.swing.JButton p91;
    private javax.swing.JButton p92;
    private javax.swing.JButton p93;
    private javax.swing.JButton p94;
    private javax.swing.JButton p95;
    private javax.swing.JButton p96;
    private javax.swing.JButton p97;
    private javax.swing.JButton p98;
    private javax.swing.JButton p99;
    private javax.swing.JTextField txtConfirmacion;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword2;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser2;
    // End of variables declaration//GEN-END:variables
}
